### ISSUE TITLE
Verktyg för att underlätta extrahering av artiklar/textblock i Courier

### ISSUE THREAD

**Issue by fredrik1984** [inidun/unesco_data_collection#1]
1. Inventera olika verktyg för att extrahera ut text ut Courier. Syftet är att hitta verktyg som kan underlätta arbetet att identifiera och extrahera ut enskilda artiklar, alternativt textblock eller paragrafer. Ju mindre manuellt arbete som krävs desto bättre.

2. Pröva Tesseract på några nummer av Courier (t ex något nummer för varje årtionde). Undersök vad ocr-verktyget kan göra vad gäller att identifiera och extrahera ut enskilda artiklar, alternativt textblock eller paragrafer.

Det kommer förmodligen inte gå att identifiera hela artiklar helt automatiskt. Men vi behöver undersöka verktyg som kan underlätta det manuella arbetet. Blir det för krångligt med artiklar kan textblock eller paragrafer fungera som analysenheter istället.

**Comment by roger-mahler** [comment]
Interesting Github repository: [link](https://github.com/BobLd/DocumentLayoutAnalysis)

**Comment by roger-mahler** [comment]
Also this: [UglyToad/PdfPig](https://github.com/UglyToad/PdfPig)

**Comment by roger-mahler** [comment]
Moved to separate issue:

2. Pröva Tesseract på några nummer av Courier (t ex något nummer för varje årtionde). Undersök vad ocr-verktyget kan göra vad gäller att identifiera och extrahera ut enskilda artiklar, alternativt textblock eller paragrafer.
