### ISSUE TITLE
Inventory of candidate tools to extract text from multicolumn page (Courier)

### ISSUE THREAD

**Issue by roger-mahler** [inidun/unesco_data_collection#5]
Make an inventory of available tools, open source as well as commercial.

| Tool | Type | Platform | Tried | Candidate |
| :--------| :--------| :--------| -------- | -------- |
| [pdfminer.six](https://github.com/pdfminer/pdfminer.six) | OSS | `python` | :heavy_check_mark: | :x: |
| [pdftotext ](https://github.com/jalan/pdftotext)| OSS | `python` | :heavy_check_mark: | [note](https://github.com/inidun/unesco_data_collection/issues/5#issuecomment-767503811)
| [ABBYY FineReader](https://pdf.abbyy.com/) | :heavy_dollar_sign: |  `Desktop app`
| [Tesseract OCR](https://github.com/tesseract-ocr/tesseract) / [pytesseract ](https://github.com/madmaze/pytesseract)| OSS | `python`
| [PDFium](https://github.com/chromium/pdfium) | 
| [pdfplumber ](https://github.com/jsvine/pdfplumber)| OSS | `python` | ✔️ | ❌ [note](https://github.com/inidun/unesco_data_collection/issues/5#issuecomment-767654128)
| [PdfPig](https://uglytoad.github.io/PdfPig/) | OSS | `.NET`
| [PyMuPDF](https://github.com/pymupdf/PyMuPDF)| PyMuPDF: OSS,  MuPDF: [see](https://mupdf.com/license.html) | `python` 
| [Microsoft UniLM](https://github.com/microsoft/unilm) | OSS | `python`
| [Apache PDFBox](https://pdfbox.apache.org/) / [(python-pdfbox)](https://github.com/lebedov/python-pdfbox/) | OSS | `Java` (`python`) | ✔️ | ✔️ ⭐ 
| [PDFxStream ](https://www.snowtide.com/)| :heavy_dollar_sign: | `.NET` `Java` | 
| [PDFLib TET](https://www.pdflib.com/products/tet/) | :heavy_dollar_sign: | `various`
| ~~[SumatraPDF](https://github.com/sumatrapdfreader/sumatrapdf)~~ | OSS | `Desktop app` | | Note: Uses MuPDF
| MS Word | 💲 | `Desktop app` | ✔️ | (✔️) [note](https://github.com/inidun/unesco_data_collection/issues/5#issuecomment-768249160)
| Acrobat Pro | 💲 | `Desktop app`

Interesting reads:
 - [If identifying text structure in PDF documents is so difficult, how do PDF readers do it so well?
](https://stackoverflow.com/questions/22675690/if-identifying-text-structure-in-pdf-documents-is-so-difficult-how-do-pdf-reade?noredirect=1&lq=1)

**Comment by roger-mahler** [comment]
### pdftotext

**Comment by roger-mahler** [comment]
### pdfpblumber

Extracting text from multicolumn pages is not supported:[see issue](https://github.com/jsvine/pdfplumber/issues/244)

**Comment by roger-mahler** [comment]
MS Word 2016
[ms_word_2016.zip](https://github.com/inidun/unesco_data_collection/files/5880104/ms_word_2016.zip)

**Comment by roger-mahler** [comment]
### Apache PDF Box using python-pdfbox

[PFDBox.zip](https://github.com/inidun/unesco_data_collection/files/5880130/PFDBox.zip)

No configuration is available via the wrapper. Command line allows for page-wise page extraction. It probably is straightforward to write a dedicated wrapper that extracts, or wraps, pages.

**Comment by roger-mahler** [comment]
### PDFminer.six

[pdfminer.zip](https://github.com/inidun/unesco_data_collection/files/5880307/pdfminer.zip)

Filed for one PDF.

**Comment by aibakeneko** [comment]
### Tesseract OCR

[tesseract.zip](https://github.com/inidun/document_layout_analysis/raw/master/src/tesseract/tesseract.zip)

**Comment by aibakeneko** [comment]
PDFBox have been selected for text extraction.
