### ISSUE TITLE
Review state-of-the art of document layout analysis

### ISSUE THREAD

**Issue by roger-mahler** [inidun/unesco_data_collection#6]
- [ ] Do an systematic review of academic writing about document layout analysis
- [ ] Contact key people (librarians, researchers) that can propose solutions
- [ ] ...

**Comment by roger-mahler** [comment]
Candidate papers:

- [ ] [NDocBank: A Benchmark Dataset for Document Layout Analysis](https://arxiv.org/abs/2006.01038)

**Comment by aibakeneko** [comment]
After review we have decided to use PDFBox.
