### ISSUE TITLE
Investigate information from Github repository

### ISSUE THREAD

**Issue by roger-mahler** [inidun/unesco_data_collection#8]
This is part of gaining understanding of the problem. The repository contains a lot of information about document 
layout analysis: [BobLd/DocumentLayoutAnalysis](https://github.com/BobLd/DocumentLayoutAnalysis)

We should consider contacting the author for tips on a feasible way forward.

**Comment by aibakeneko** [comment]
Might be relevant for proceedings. Revisit then.
