### ISSUE TITLE
Create time-estimates for different approaches

### ISSUE THREAD

**Issue by roger-mahler** [inidun/unesco_data_collection#9]
Create a number of time estimates for semi-automatic text column extraction, excluding developer time, with varying degrees of quality.

 - [x] ~~Rescan of all PDFs using Tesseract with no manual interference apart from any program configuration.~~
 - [x] ~~Rescan of all PDFs using ABBYY with no manual interference apart from any program configuration.~~
 - [x] ~~Rescan and manual bounding/text box sort ordering using ABBYY Finereader Manual.~~
 - [x] ~~Fully manual text copy out from PDF-reader (e.g. Foxit, Adobe Reader, ABBYY)~~

**Comment by aibakeneko** [comment]
After evaluation we have decided to use PDFBox.
